@__HostAddress = http://localhost:5009

### Health Check
GET {{__HostAddress}}/health
Accept: application/json

###

### Health Check (Ready)
GET {{__HostAddress}}/health/ready
Accept: application/json

###

### Database Connection Test
GET {{__HostAddress}}/db/test
Accept: application/json

###
